### ISSUE TITLE
Feature Request: deftype for raw non-dispatchable handle

### ISSUE THREAD

**Issue by scgehin** [JolifantoBambla/vk#10]
I'd like to be able to declare the types of arguments for a function that is working with raw-handles. The type of a non-dispatchable handle is platform dependent, so it would be nice if vk could expose the type itself since it has already figured it out.

**Comment by JolifantoBambla** [comment]
You're talking about the [type declared here](https://github.com/JolifantoBambla/vk/blob/89fdc3278cb7696e2f5b1a46fb4d7f215ef1428d/src/vk-handle.lisp#L17) and not the `%non-dispatchable` struct, right?

**Comment by scgehin** [comment]
Correct.

**Comment by JolifantoBambla** [comment]
the type `non-dispatchable-handle` is exposed by `vk` in version 3.1.0-v1.2.198
