### ISSUE TITLE
descriptor-set-layout-binding slot immutable-samplers only takes one sampler.

### ISSUE THREAD

**Issue by scgehin** [JolifantoBambla/vk#11]
The vulkan specification states that pImmutableSamplers must be either NULL or "a valid pointer to an array of descriptorCount valid VkSampler handles" [here](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayoutBinding.html).

The docstring for vk:descriptor-set-binding states that IMMUTABLE-SAMPLERS is an optional sampler, singular. Trying to pass in a list results in an error such as ``
The value
  (#S(VK:SAMPLER :HANDLE #.(SB-SYS:INT-SAP #XFAB64D0000000002)))
is not of type
  VK::%NON-DISPATCHABLE
``.

## Environment
* `vk` version: vk-20220707-git (quicklisp)
* CL implementation (name & version): SBCL 2.2.4
* OS: Funtoo Linux

**Comment by JolifantoBambla** [comment]
thanks for reporting!
the translation of the `immutable-samplers` member in `descriptor-set-layout-binding` should be fixed in version 3.1.0-v1.2.198
