### ISSUE TITLE
vk:get-physical-device-surface-capabilities-khr can not make it's result

### ISSUE THREAD

**Issue by Gammamad** [JolifantoBambla/vk#12]
When called vk:get-physical-device-surface-capabilities-khr throws error, not being able to initialize result.

## Environment
* `vk` version: vk-20221106-git (via quicklisp)
* CL implementation (name & version): SBCL 2.2.11
* OS: Gentoo Linux 6.1.0-gentoo

## How to reproduce the issue
;; vk-surface contains vk:physical-device and vk:surface-khr, which are passed to vk:get-physical-device-surface-capabilities-khr
(defun get-surface-capabilities(vk-surface)
  (vk:get-physical-device-surface-capabilities-khr
   (vk-surface-physical-device vk-surface)
   (vk-surface-surface vk-surface)))

## Expected behavior
vk:get-physical-device-surface-capabilities-khr returns capabilities structure.

## Actual behavior
Compiled successfully, but when run error occurs:
0 is not defined as a value for enum type #<CFFI::FOREIGN-ENUM VULKAN:SURFACE-TRANSFORM-FLAG-BITS-KHR>.
   [Condition of type SIMPLE-ERROR]

**Comment by Gammamad** [comment]
Turns out it's my error.

**Comment by JolifantoBambla** [comment]
Glad you could solve it :)
