### ISSUE TITLE
Error on creating instance

### ISSUE THREAD

**Issue by Guthur** [JolifantoBambla/vk#6]
## Environment
* `vk` version: Current (quicklisp)
* CL implementation (name & version): SBCL 2.1.1
* OS: Ubuntu (21.04)

If it's not purely CL-related, please add:
* Vulkan lib version: ...
* Graphics driver: ...

## How to reproduce the issue
Using the test code from VK or 01 from VK samples

## Expected behavior
Creating and instance

## Actual behavior
Can not find the correct dynamic function for `cffi:translate-into-foreign-memory`

## Additional context
Looks like its not using the correct type class, %vk are all `c-<struct name>` and the translation functions appear to be `<struct-name>`

**Comment by Guthur** [comment]
Seems if i rename the :class on the defcstruct to remove the `c-` it works. Did this naming scheme get changed recently?

**Comment by JolifantoBambla** [comment]
Oh man, that's strange. The `c-`-prefixes have been there from the start and the translator methods also specialize on the `c-`-prefixed class names.
I tried to reproduce this issue earlier today with a fresh install of SBCL and Quicklisp on Ubuntu 20.04 and Windows 10 by running all samples (also fresh pulls of all necessary external repositories and no other systems than `vk` and `vk-samples` explicity `ql:quickload`ed) and the test case and everything worked fine. 
It's pretty late for me (CET), but I'll try again with your setup tomorrow.
I guess your Quicklisp is up to date?

**Comment by Guthur** [comment]
Yeah up to date. Let me try the again, but it's a odd that i've got it to work by renaming

**Comment by Guthur** [comment]
@JolifantoBambla so sorry for wasting your time, this was totally my fault. I had started crafting some of my own adhoc bindings in by project and I think it had silently shadowed your symbols, doh.

Again my apologies for taking your time, and thanks so much for looking and providing these bindings.

**Comment by JolifantoBambla** [comment]
@Guthur No worries, glad it works now. I hope it fits your needs :)
