### ISSUE TITLE
device-queue-create-info missing queue-count member

### ISSUE THREAD

**Issue by scgehin** [JolifantoBambla/vk#7]
device-queue-create-info only has four slots. An equivalent of queueCount is not available. I suspect it was mistaken for a "length" parameter for another field. queueCount actually specifies the number of new queues to be created, not the number of anything being passed in.

## Environment
* `vk` version: vk-20220220-git from quicklisp
* CL implementation (name & version): SBCL 1.5.3
* OS: Funtoo Linux

## Expected behavior
device-queue-create-info should have a queue-count slots, or similar. make-device-queue-create-info should also allow for initializing it.

## Actual behavior
No such thing exists.

**Comment by scgehin** [comment]
I see now that it is getting the count from the queue-priorities slot. Sorry for any inconvenience.

**Comment by JolifantoBambla** [comment]
No worries, I know that parts of this lib can be confusing. I'll add this to the caveats section of the readme later.
