### ISSUE TITLE
fail to set image-blit

### ISSUE THREAD

**Issue by aiffc** [JolifantoBambla/vk#8]
## Environment
* `vk` version: newest
* CL implementation (name & version): sbcl
* OS: linux

If it's not purely CL-related, please add:
* Vulkan lib version: newest
* Graphics driver: gtx 1050ti

## How to reproduce the issue
when i tried to use function vk:cmd-blit-image i found a error, then a try something,

i found in function foreign-allocate-and-fill :
(array-type (alexandria:flatten (list :array type (array-dimensions content))))

if the type is a struct it will be wrong so i tried change it to this 
(array-type \`(:array ,type ,@(alexandria:flatten (array-dimensions content))))
it worked but when i used (cffi:mem-ref cimage-blit '(:struct %vk:image-blit)) to dump the value of src-offset[1] and dst-offset[2], i found they are wrong.

here is my test code.

`
;;;;;;;;;;;;;;;;;;;;;;;;;;;before change;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter src-offset0 (vk:make-offset-3d :x 100 :y 100 :z 0))

(defparameter src-offset1 (vk:make-offset-3d :x 200 :y 200 :z 1))

(defparameter dst-offset0 (vk:make-offset-3d :x 300 :y 300 :z 0))

(defparameter dst-offset1 (vk:make-offset-3d :x 400 :y 400 :z 1))

(defparameter cimage-blit (cffi:foreign-alloc '(:struct %vk:image-blit)))

(defparameter image-blit (vk:make-image-blit\
	    :src-offsets (vector src-offset0 src-offset1)
	    :src-subresource (vk:make-image-subresource-layers
			      :aspect-mask :color
			      :mip-level 0
			      :base-array-layer 0
			      :layer-count 1)
	    :dst-offsets (vector dst-offset0 dst-offset1)
	    :dst-subresource (vk:make-image-subresource-layers
			      :aspect-mask :color
			      :mip-level 1
			      :base-array-layer 0
			      :layer-count 1)))
(setf (cffi:mem-ref cimage-blit '(:struct %vk:image-blit))
	       image-blit)`

then i get an error 

invalid number of arguments: 0
   [Condition of type SB-INT:SIMPLE-PROGRAM-ERROR]

Restarts:
 0: [REPLACE-FUNCTION] Call a different function with the same arguments
 1: [CALL-FORM] Call a different form
 2: [RETRY] Retry SLY mREPL evaluation request.
 3: [*ABORT] Return to SLY's top level.
 4: [ABORT] abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {10020ED543}>)

Backtrace:
 0: ((LAMBDA (CFFI::NAME) :IN "/home/aif/.quicklis-package/sbcl-package/dists/quicklisp/software/cffi_0.24.1/src/types.lisp")) [external]
 1: (CFFI::PARSE-TYPE :STRUCT)
 2: ((:METHOD CFFI:FOREIGN-TYPE-SIZE (T)) :STRUCT) [fast-method]
 3: ((:METHOD CFFI:FOREIGN-TYPE-SIZE (CFFI::FOREIGN-ARRAY-TYPE)) #<CFFI::FOREIGN-ARRAY-TYPE :STRUCT (VULKAN:OFFSET-3D 2)>) [fast-method]
 4: (CFFI:FOREIGN-ALLOC (:ARRAY :STRUCT VULKAN:OFFSET-3D 2) :INITIAL-ELEMENT NIL :INITIAL-CONTENTS NIL :COUNT 2 :NULL-TERMINATED-P NIL)
 5: (VK-ALLOC:FOREIGN-ALLOCATE-AND-FILL (:STRUCT VULKAN:OFFSET-3D) #((OFFSET-3D:x 100:y 0:z 0) (OFFSET-3D:x 200:y 200:z 1)) #.(SB-SYS:INT-SAP #X7F02AC031690))
 6: ((LAMBDA ()))
 7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SETF (CFFI:MEM-REF CIMAGE-BLIT (QUOTE #)) IMAGE-BLIT) #<NULL-LEXENV>)
 8: (EVAL (SETF (CFFI:MEM-REF CIMAGE-BLIT (QUOTE #)) IMAGE-BLIT))
 9: ((LAMBDA NIL :IN SLYNK-MREPL::MREPL-EVAL-1))
 --more--
;;;;;;;;;;;;;;;;;;;;;;;;;;;after change the src-offset[1] and dst-offset[1] are wrong;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CL-USER> image-blit
(IMAGE-BLIT
 :src-subresource (IMAGE-SUBRESOURCE-LAYERS
                   :aspect-mask :COLOR
                   :mip-level 0
                   :base-array-layer 0
                   :layer-count 1)
 :src-offsets #((OFFSET-3D
                 :x 100
                 :y 100
                 :z 0)
                (OFFSET-3D
                 :x 200
                 :y 200
                 :z 1))
 :dst-subresource (IMAGE-SUBRESOURCE-LAYERS
                   :aspect-mask :COLOR
                   :mip-level 1
                   :base-array-layer 0
                   :layer-count 1)
 :dst-offsets #((OFFSET-3D
                 :x 300
                 :y 300
                 :z 0)
                (OFFSET-3D
                 :x 400
                 :y 400
                 :z 1)))
CL-USER> (setf (cffi:mem-ref cimage-blit '(:struct %vk:image-blit))
	       image-blit)
(IMAGE-BLIT
 :src-subresource (IMAGE-SUBRESOURCE-LAYERS
                   :aspect-mask :COLOR
                   :mip-level 0
                   :base-array-layer 0
                   :layer-count 1)
 :src-offsets #((OFFSET-3D
                 :x 100
                 :y 100
                 :z 0)
                (OFFSET-3D
                 :x 200
                 :y 200
                 :z 1))
 :dst-subresource (IMAGE-SUBRESOURCE-LAYERS
                   :aspect-mask :COLOR
                   :mip-level 1
                   :base-array-layer 0
                   :layer-count 1)
 :dst-offsets #((OFFSET-3D
                 :x 300
                 :y 300
                 :z 0)
                (OFFSET-3D
                 :x 400
                 :y 400
                 :z 1)))
CL-USER> (cffi:mem-ref cimage-blit '(:struct %vk:image-blit))
(IMAGE-BLIT
 :src-subresource (IMAGE-SUBRESOURCE-LAYERS
                   :aspect-mask (:COLOR)
                   :mip-level 0
                   :base-array-layer 0
                   :layer-count 1)
 :src-offsets ((OFFSET-3D
                :x 100
                :y 100
                :z 0)
               (OFFSET-3D
                :x 1148347764
                :y 6517605
                :z 1651076143))
 :dst-subresource (IMAGE-SUBRESOURCE-LAYERS
                   :aspect-mask (:COLOR)
                   :mip-level 1
                   :base-array-layer 0
                   :layer-count 1)
 :dst-offsets ((OFFSET-3D
                :x 300
                :y 300
                :z 0)
               (OFFSET-3D
                :x 892235635
                :y 1811951616
                :z 1970692713)))
CL-USER> 
`
## Expected behavior
set the dst-offset[1] and src-offset[1] currectly 

## Actual behavior
It's looks like dst-offset[1] and src-offset[1] are not be processed after set.

**Comment by aiffc** [comment]
(setf (cffi:mem-aref (cffi:foreign-slot-pointer cimage-blit
						    '(:struct %vk:image-blit)
						    '%vk:src-offsets)
			 '(:struct %vk:offset-3d) 0)
	  src-offset0
	  (cffi:mem-aref (cffi:foreign-slot-pointer cimage-blit
						    '(:struct %vk:image-blit)
						    '%vk:src-offsets)
			 '(:struct %vk:offset-3d) 1)
	  src-offset1
	  (cffi:mem-aref (cffi:foreign-slot-pointer cimage-blit
						    '(:struct %vk:image-blit)
						    '%vk:dst-offsets)
			 '(:struct %vk:offset-3d) 0)
	  dst-offset0
	  (cffi:mem-aref (cffi:foreign-slot-pointer cimage-blit
						    '(:struct %vk:image-blit)
						    '%vk:dst-offsets)
			 '(:struct %vk:offset-3d) 1)
	  dst-offset1)

this will be ok, it's looks like you should get the array first, then use the value to fill it.

**Comment by JolifantoBambla** [comment]
Hey, thanks for reporting this! I'll fix it later this week.
As a workaround, you can work with lists in the meantime if that's not too much of a hassle.

**Comment by JolifantoBambla** [comment]
Been sick the last few days :/
I'll get to it sometime this week.

The problem is that I assign the pointer returned by `allocate-and-fill` to the slotpointer during translation, but I should just use the slotpointer and call `cffi:lisp-array-to-foreign` directly.
This affects all structs that have fixed sized array slots with non-primitive elements (for primitive fixed sized arrays like `matrix` in `transform-matrix-khr` this is already done), i.e. the structs related to the image blit commands and the ones provided by the `VK_KHR_frament_shading_rate` extension and its predecessor.

**Comment by aiffc** [comment]
Thanks for you help and hope you feel better soon.
I found this issue by vulkan debug layers, so i tried these tests. by the way i tried to use lists but the result looks same. I think the reason is the same.

**Comment by JolifantoBambla** [comment]
Thanks :)

> i tried to use lists but the result looks same. I think the reason is the same.

Yes, that's correct.

**Comment by JolifantoBambla** [comment]
should be fixed in 3.0.1
https://github.com/JolifantoBambla/vk/tree/3.0.1-v1.2.198

**Comment by aiffc** [comment]
yes, it works well now. Thanks
